docker:
  - image: circleci/openjdk:11-jdk
working_directory: ~/ircWebBot
environment:
  JVM_OPTS: -Xmx3200m
  TERM: dumb
steps:
  - irc_notify:
      message: "I am starting a build on $CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH branch -> https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID"
  - checkout:
      path: ~/ircWebBot
  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  - run: gradle dependencies
  - save_cache:
      paths:
        - ~/.gradle
      key: v1-dependencies-{{ checksum "build.gradle" }}
  - run: gradle build
  - run: gradle bootJar
  - run: gradle properties -q | grep "version:" | awk '{print $2}' | tr -d '[:space:]' >> version
  - persist_to_workspace:
      root: ~/ircWebBot
      paths:
        - Dockerfile
        - build/libs
        - build/resources
        - version