docker:
  - image: circleci/python
working_directory: ~/ircWebBot/.circleci
steps:
  - checkout:
      path: ~/ircWebBot
  - run: python check_config.py
  - run:
      name: Halt and commit when config changed
      command: |
          curl -X POST https://$WEBIRC_URL/sendMsg -H "Content-Type: application/json" -d "{\"password\":\"$WEBIRC_PASSWORD\", \"channel\":\"$IRC_CHANNEL\", \"key\":\"$IRC_KEY\", \"message\":\"Hey Smither, the circle config is outdated. Just fixing it now. Hold on to something....\"}"
          git config --global user.email "$GITHUB_EMAIL"
          git config --global user.name "$CIRCLE_USERNAME"
          git add config.yml
          git commit -m "Config Changed: Updating Circle build Config
            https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_ID
          "
          git push -q https://${GITHUB_TOKEN}@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git $CIRCLE_BRANCH
      when: on_fail
