docker:
  - image: circleci/python
steps:
  - attach_workspace:
      at: ./artifacts
  - irc_notify:
      run: export VERSION=$(cat ./artifacts/.version)
      message: "$CIRCLE_PROJECT_REPONAME has a new release! Version $VERSION is available NOW!"