docker:
  - image: circleci/openjdk:11-jdk
working_directory: ~/ircWebBot
environment:
  JVM_OPTS: -Xmx3200m
  TERM: dumb
steps:
  - checkout:
      path: ~/ircWebBot
  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
  - run: gradle dependencies
  - save_cache:
      paths:
        - ~/.gradle
      key: v1-dependencies-{{ checksum "build.gradle" }}
  - run: gradle check
  - store_artifacts:
      path: build/reports
      destination: reports
  - store_test_results:
      path: build/test-results
  - irc_notify:
      message: "Tests PASSED on $CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH. See results HERE -> https://$CIRCLE_BUILD_NUM-$CIRCLE_WORKFLOW_ID-gh.circle-artifacts.com/0/reports/tests/test/index.html"
  - irc_notify:
      message: "Tests PASSED on $CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH. See results HERE -> https://$CIRCLE_BUILD_NUM-$CIRCLE_PROJECT_NUM-gh.circle-artifacts.com/0/reports/tests/test/index.html"
  - run:
      name: Report Failure to IRC
      command: |
        curl -X POST https://$WEBIRC_URL/sendMsg -H "Content-Type: application/json" -d "{\"password\":\"$WEBIRC_PASSWORD\", \"channel\":\"$IRC_CHANNEL\", \"key\":\"$IRC_KEY\", \"message\":\"Tests FAILED on $CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH. See results HERE -> https://$CIRCLE_BUILD_NUM-$CIRCLE_PROJECT_NUM-gh.circle-artifacts.com/0/reports/tests/test/index.html\"}"
      when: on_fail