version: 2.1

commands: {{commands}}

jobs: {{jobs}}

workflows:
  version: 2.1
  server:
    jobs:
      - check_circle_config
      - build_server:
          requires:
            - check_circle_config
      - test_server:
          requires:
            - build_server
      - request_approval:
          requires:
            - test_server
          filters:
            branches:
              only:
                - master
      - release_approval:
          type: approval
          requires:
            - request_approval
      - docker_release:
          requires:
            - release_approval
      - publish_github_release:
          requires:
            - release_approval
      - notify_release:
          requires:
            - docker_release
            - publish_github_release